# Generated by Django 2.1.3 on 2019-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190123_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
