# Generated by Django 2.1.3 on 2019-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(default='aaa', max_length=20),
            preserve_default=False,
        ),
    ]
