# Generated by Django 2.1.3 on 2019-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_no',
            field=models.PositiveIntegerField(default=9130899800, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
