# Generated by Django 2.1.3 on 2019-01-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20190127_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
