# Generated by Django 2.1.3 on 2021-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20190203_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
