# Generated by Django 2.1.3 on 2019-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
