# Generated by Django 2.1.3 on 2019-01-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
