# Generated by Django 2.1.3 on 2019-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190123_1027'),
        ('carts', '0007_auto_20190123_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='products',
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
