# Generated by Django 2.1.3 on 2019-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20190125_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='Item',
            field=models.ManyToManyField(null=True, to='carts.Item'),
        ),
    ]
