# Generated by Django 2.1.3 on 2019-01-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190123_1027'),
        ('carts', '0010_remove_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='products',
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
