# Generated by Django 2.1.3 on 2019-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190123_1027'),
        ('carts', '0014_auto_20190128_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
