# Generated by Django 2.1.3 on 2019-01-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
    ]
