# Generated by Django 2.1.3 on 2019-01-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20190129_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_in_cart',
            field=models.ManyToManyField(to='carts.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='cart_in_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='item',
            name='line_item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
