# Generated by Django 2.1.3 on 2019-01-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190123_1027'),
        ('carts', '0021_auto_20190129_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ManyToManyField(blank=True, null=True, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
