# Generated by Django 2.1.3 on 2019-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_auto_20190130_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
