# Generated by Django 2.1.3 on 2019-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_item_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='carts.Item'),
        ),
    ]
