# Generated by Django 2.1.3 on 2019-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0026_auto_20190130_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
