# Generated by Django 2.1.3 on 2021-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_auto_20190130_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='carts.Item'),
        ),
    ]
