# Generated by Django 2.1.3 on 2019-01-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_auto_20190123_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_pdf', models.FileField(upload_to='static_cdn/media_root')),
                ('order_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
